AWSTemplateFormatVersion: '2010-09-09'

Description: Proxy Sock5 infrastructure as code templates

Parameters:
  KeyName:
    Type: String
  InstanceType:
    Description: "EC2 instance type."
    Default: t2.micro
    ConstraintDescription: 'must be a valid EC2 instance type.'
    Type: String
    AllowedValues:
      - t2.nano
      - t2.micro
      - t3.micro
  AmiId:
    Description: 'AMI id for Coda server.'
    Type: AWS::EC2::Image::Id
  ProxyMinSize:
    Description: 'The Min Size for the Privoxy AutoScale group.'
    Type: Number
    Default: 1
  ProxyMaxSize:
    Description: 'The Max Size for the Privoxy AutoScale group.'
    Type: Number
    Default: 1
  ProxyPort:
    Description: 'Your Privoxy port number'
    Type: Number
    Default: 1080
  NumberOfAZs:
    Description: 'The Max NUmber of Subnets (one by AZ)'
    Type: Number
    Default: 1
  NightlyOut:
    Type: String
    Description: "stop instance on evening"
    Default: 'false'

Resources:
  VpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: vpc.yml
      TimeoutInMinutes: 60
      Parameters:
        RegionAzs: !Ref NumberOfAZs

  Autoscalling:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VpcStack
    Properties:
      TemplateURL: autoscalling.yml
      TimeoutInMinutes: 30
      Parameters:
        VpcId: !GetAtt VpcStack.Outputs.Vpc
        AmiId: !Ref AmiId
        ProxyPort: !Ref ProxyPort
        KeyName: !Ref KeyName
        MinSize: !Ref ProxyMinSize
        MaxSize: !Ref ProxyMaxSize
        InstanceType: !Ref InstanceType
        Subnets: !GetAtt VpcStack.Outputs.PublicSubnets
        AvailabilityZones: !GetAtt VpcStack.Outputs.AvailabilityZones
        NightlyOut: !Ref NightlyOut

  UserStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - Autoscalling
    Properties:
      TemplateURL: user.yml
      TimeoutInMinutes: 60
      Parameters:
        AutoscallingGroup: !GetAtt Autoscalling.Outputs.AutoScalingGroup

Outputs:
  ManagerUserAccessKey:
    Description: "Manager user Access Key"
    Value: !GetAtt UserStack.Outputs.ManagerUserAccessKey
  ManagerUserSecretKey:
    Description: "Manager user Secret Key"
    Value: !GetAtt UserStack.Outputs.ManagerUserSecretKey
  PublisDNS:
    Value: !GetAtt Autoscalling.Outputs.PublisDNS
  AutoscallingGroupId:
    Value: !GetAtt Autoscalling.Outputs.AutoScalingGroup
  PrivoxyPort:
    Value: !Ref ProxyPort