on:
  release:
    types: [created]

name: Deploy to Cloudformation

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
          echo "[github]" > ~/.aws/credentials
          echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
          echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
          echo "[profile github]" > ~/.aws/config
          echo "region=$AWS_REGION" >> ~/.aws/config

    - name: Deploy Cloudformation
      env:
        AWS_PROFILE: github
        AWS_REGION: ${{ secrets.AWS_REGION }}
        ROLE_ARN: ${{ secrets.ROLE_ARN }}
        BUCKET: ${{ secrets.BUCKET }}
        AWS_KEY_NAME: ${{ secrets.AWS_KEY_NAME }}
        PrivoxyPort: ${{ secrets.PRIVOXY_PORT }}
      run: |
        export NbAzs=$(sh ./bin/getRegionAzs.sh $AWS_PROFILE $AWS_REGION)
        export AWS_SOURCE_AMI=$(sh ./bin/detect-ami.sh $AWS_PROFILE $AWS_REGION)
        make deploy
        make describe
